"""empty message

Revision ID: 4c084cbe93dc
Revises: 7f2796ee3d61
Create Date: 2024-05-26 15:08:24.990023

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4c084cbe93dc'
down_revision = '7f2796ee3d61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('genre', sa.String(length=100), nullable=False))
        batch_op.alter_column('cover_image',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=255),
               nullable=False)
        batch_op.alter_column('classification',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=100),
               nullable=False)
        batch_op.alter_column('release_date',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('synopsis',
               existing_type=mysql.TEXT(collation='utf8mb4_general_ci'),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.alter_column('synopsis',
               existing_type=mysql.TEXT(collation='utf8mb4_general_ci'),
               nullable=True)
        batch_op.alter_column('release_date',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('classification',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=100),
               nullable=True)
        batch_op.alter_column('cover_image',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=255),
               nullable=True)
        batch_op.drop_column('genre')

    # ### end Alembic commands ###
